### ISSUE TITLE
Burrows-Wheeler

### ISSUE THREAD

**Issue by akamiru** [thinknlive/picolisp-bbwt#1]
*I can't look at lisp without getting a headache so this issue refers completly to the article you claim to implement:*

----
This isn't actually doing a *Burrows Wheeler transform*. 

It does an *order-1 Schindler transform* (which is patented since 2001): 
It only partly sorts the rotations (by its first character) not the whole rotation. Since every single character is in fact a lyndon word itself what you are describing is basically a scottified (named after David Scott who invented the orginal BWTS) order-1 Schindler transform. 

Sadly *order-1 Schindler transform* is pretty useless for compression. It achieves only first order entropy (about 50% reduction for english text) compared to >80% for the full order burrows wheeler. Note that these numbers are asymptotic which means the difference doesn't show for short string because they don't contain long common prefixes.

While order-1 compression itself is a nice thing to have (e.g. zip only uses order-0) it can be done much simpler by using bounded markov chains. An example is google's new brotli compression which uses order-2 without a sort transform.

----

Another note on the overhead of the lyndon factorization: The factorization itself causes almost no overhead: It runs at a few GB/s while the Burrows Wheeler transform in it's fastest form (via the suffix array) runs at around a few MB/s. There's actually some clever code which reorders the suffix array to its scottified version with not too much overhead (https://code.google.com/archive/p/mk-bwts/).

**Comment by thinknlive** [comment]
Thanks for commenting.  That is interesting information I'll have to spend time reading up on. The author of the article I referred gave a clear, at least to me,  explanation of how the transform works. It was a good programming exercise to write an implementation from that description.

**Comment by akamiru** [comment]
Keep it up ! Feel free to ask questions !

You might be interessted in my novel [suffix array construction algorithm](https://github.com/akamiru/sort) or my BWT based implementation of Compression via Substring Enumeration [BCE](https://github.com/akamiru/bce). Both of which are heavy theoretical beasts and I had a lot of fun working them out over the last few years.

**Comment by thinknlive** [comment]
_I can't look at C++ without...._ :)  You have sparked my interest though! One thought I had that followed from playing with the BWT and reading up a bit is that it may make a good adaptive model for an arithmetic coder. It is essentially a graph. If you keep counts of distinct edge values on a node it may be possible to obtain a better probability of the next value to encode...  "Hey Ferb! I know what we're gonna do today".

**Comment by akamiru** [comment]
Wow this got longer than expected:

:D I totally understand that. I have trouble looking even at C. 

My SACA has a rather high-level description in it's wiki. It first sorts all lyndon words starting at each offset and than finishs sorting in a single run over the array. It builds on ideas of a paper from last year called [GSACA](https://github.com/waYne1337/gsaca). You might want to read about suffix arrays and some suffix array construction algorithms first (prefix doubling, SAIS).

BCE has a high-level description on [encode.ru](https://encode.ru/threads/2150-A-new-algorithm-for-compression-using-order-n-models) (you might be interessted in this board: a lot of good ideas emerged there e.g. Yann Collet's [zstd](https://github.com/facebook/zstd) (now facebook's zstd)). Basically it counts every binary substring and encodes how often it can be found. The hard part here is to get that working in linear time. My first version needed around 2000s for 1GB the version I currently develop needs around 15s (both times additionally to the burrows wheeler transform). Both versions are developed in C++ and there are no algorithmic improvements that speed them up. Most practical compression algorithms are written in C due to the *Need for Speed*. So you might want to grap yourself some aspirin.

There are some papers on it where it's called Compression via Substring Enumeration (CSE). It took me 2 years after my initial release to find out about it. Still I was almost 2 years faster at implementing it practical (so I got that going for me which is nice) than the first papers but anyway: It's always good to check what others did first. 

Keeping a graph to encode is basically markov coding (and bce can be viewed as recursively refining a markov graph) so you might be on the same way I was. Dynamic markov coding for example builds a graph while compressing to learn the distributions. Basic problem with BWT is that it's *non adaptive* you have basically no knowledge where the char your currently encoding is in the original text. Therefore you can't use local differences e.g. a text inside xml maybe better compressed as text and xml separated.

[Matt Mahoney's book on compression](http://mattmahoney.net/dc/dce.html) is *definitely* worth reading to get a good overview. It's also has indept description of PAQ (a series of the best compressors currently available which he developed) and gives a good overview over the current state of art. It mostly misses the latest development: a section on CSE/Antidictionary coding and Asymmetric Numeral Systems (the thing that gives zstd and apple's lzfse its speed).

I have no idea on which level of knowledge you currently are so these are some general starting points. I hope its helpfull.

**Comment by thinknlive** [comment]
This is going to be awesomely addictive. Thanks for sharing. I came across Mahoney's book a while ago but paid it cursory attention at the time... Recently I decided it was time to make a serious effort to learn Lisp... and was looking for interesting algorithmic problems to tackle... i.e. not yet another crm or todo list. The choices came down to crypto or lossless data compression.  Both require manipulating 'lists' or streams of symbols in novel ways. There is something fundamentally gratifying in good data compression and, in a sense, it is crypto if a complex dictionary is required to reverse the process.... and successfully reversing the process is the definitive unit test and unavoidable =)

**Comment by akamiru** [comment]
Cryptography is definitely another interessting topic ! Parsing is btw another really interesting topic. Especially because it's quite related to compression in the sense that the better you understand the text the better you can compress it and parsing is basically a way to understand a text algorithmically.

Moreover it's a good start into compiler construction a topic which helps you to understand what compilers do and how you get them to emit faster code.
